apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.name" . }}-config
  labels:
    app.kubernetes.io/name: {{ template "app.name" . }}
    {{- include "app.labels" . | nindent 4 }}
data:
  appsettings.json: |
    {
      "AllowedHosts": "*",
      "JsonIngestionConfiguration": {
        "BufferSize": {{ .Values.settings.bufferSize }},
        "ThrottleDocumentLimit": {{ .Values.settings.throttleDocumentLimit }},
        "ThrottleDocumentBurst": {{ .Values.settings.throttleDocumentBurst }},
        "ThrottleTimespan": {{ .Values.settings.throttleTimespan | quote }},
        "MaxDocumentsPerFile": {{ .Values.settings.maxDocumentsPerFile }},
        "GroupingInterval": {{ .Values.settings.groupingInterval | quote }},
        "IngestionSinkPath": {{ .Values.settings.ingestionSinkPath | quote }}
      },
    }
