apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.name" . }}-ingestion
  labels:
    app.kubernetes.io/name: {{ template "app.name" . }}
    {{- include "app.labels" $ | nindent 4 }}
    {{- include "app.tracerIngestionLabels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        {{- include "app.tracerIngestionLabels" $ | nindent 8 }}
      annotations:
        deployment/date: {{ now }}
    spec:
      serviceAccountName: {{ template "app.serviceAccountName" . }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: {{ .Values.nodes.taint }}
                  operator: In
                  values:
                  - {{ .Values.nodes.taintValue }}
      tolerations:
        - key: {{ .Values.nodes.taint }}
          operator: Equal
          value: {{ .Values.nodes.taintValue }}
          effect: NoSchedule
      containers:
      - name: arcane
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
              - /bin/bash
              - '-c'
              - |
                
                curl --fail http://localhost:80/health

          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 10
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: {{ .Values.environment }}
          - name: APPLICATION_VERSION
            value: {{ .Values.image.tag }}
          - name: APPLICATION_HOST_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: PROTEUS__DATADOG_SITE
            value: {{ .Values.logs.datadogSite }}
          - name: PROTEUS__DEFAULT_LOG_LEVEL
            value: {{ .Values.logs.logLevel | quote }}
        {{- if .Values.extraEnvFrom }}
        envFrom:
          {{- with .Values.extraEnvFrom }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- end }}
        volumeMounts:
        - name: arcane-config
          mountPath: /app/appsettings.json
          subPath: appsettings.json
        {{- with .Values.extraVolumeMounts }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        resources:
          limits:
            cpu: {{ .Values.limits.ingestion.cpu }}
            memory: {{ .Values.limits.ingestion.memory }}
          requests:
            cpu: {{ .Values.limits.ingestion.cpu }}
            memory: {{ .Values.limits.ingestion.memory }}
      volumes:
      - name: arcane-config
        configMap:
          name: {{ template "app.name" . }}-config
      {{- if .Values.extraVolumes }}
        {{- with .Values.extraVolumes }}
          {{- toYaml . | nindent 6 }}
        {{- end }}
      {{- end }}
