apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "app.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ template "app.serviceAccountName" . }}
    {{- include "app.labels" $ | nindent 4 }}
