apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "app.name" . }}
    {{- include "app.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ template "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
