apiVersion: v2
name: arcane-ingestion
description: |
  Arcane is a Akka.NET-based data ingestion service that can be used to ingest data from various sources and store it in a data lake.
  This chart deploys the Arcane Ingestion service.
type: application
version: 0.0.0
appVersion: "0.0.0"

keywords:
  - dotnet
  - streaming
  - akka.net
  - data-ingestion

sources:
  - https://github.com/SneaksAndData/arcane-ingestion

maintainers:
  - name: Sneaks&Data (part of Ecco A/S)
    url: https://github.com/SneaksAndData
    email:  esdsupport@ecco.com
